"""
Send the daily digest. Reads mentions.jsonl, picks rows with first_seen
inside the configurable window (default 24h), groups by category, sends
one HTML email via SMTP.

Env vars required:
    DIGEST_SMTP_HOST, DIGEST_SMTP_PORT, DIGEST_SMTP_USER, DIGEST_SMTP_PASS,
    DIGEST_FROM, DIGEST_TO

If no new mentions in the window, exits 0 silently (no empty digest spam).
"""

from __future__ import annotations

import html
import json
import os
import smtplib
import sys
from collections import defaultdict
from datetime import datetime, timedelta, timezone
from email.message import EmailMessage
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
STATE = ROOT / "reports" / "mentions.jsonl"

WINDOW_HOURS = float(os.environ.get("DIGEST_WINDOW_HOURS", "24"))

CATEGORY_ORDER = [
    "regional_press",
    "tech_press_mena",
    "tech_press_global",
    "islamic_finance_press",
    "linkedin",
    "social_x",
    "catch_all",
]

CATEGORY_LABEL = {
    "regional_press": "Regional press (Gulf)",
    "tech_press_mena": "Tech press (MENA)",
    "tech_press_global": "Tech press (global)",
    "islamic_finance_press": "Islamic finance press",
    "linkedin": "LinkedIn",
    "social_x": "X / Twitter",
    "catch_all": "Other",
}


def load_recent(window_hours: float) -> list[dict]:
    if not STATE.exists():
        return []
    cutoff = datetime.now(timezone.utc) - timedelta(hours=window_hours)
    out: list[dict] = []
    with STATE.open() as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                row = json.loads(line)
                if datetime.fromisoformat(row["first_seen"]) >= cutoff:
                    out.append(row)
            except (json.JSONDecodeError, KeyError, ValueError):
                continue
    return out


def render_html(rows: list[dict]) -> str:
    by_cat: dict[str, list[dict]] = defaultdict(list)
    for r in rows:
        by_cat[r["category"]].append(r)

    today = datetime.now(timezone.utc).strftime("%a %d %b %Y")
    parts = [
        "<html><body style=\"font-family: -apple-system, system-ui, sans-serif;"
        " max-width: 720px; margin: 0 auto; color: #111;\">",
        f"<h2 style=\"margin-bottom:4px\">Mal monitoring — {html.escape(today)}</h2>",
        f"<p style=\"color:#666;margin-top:0\">{len(rows)} new mention(s) "
        f"in the last {WINDOW_HOURS:g}h.</p>",
    ]

    for cat in CATEGORY_ORDER:
        items = by_cat.get(cat, [])
        if not items:
            continue
        parts.append(
            f"<h3 style=\"border-bottom:1px solid #ddd;padding-bottom:4px\">"
            f"{html.escape(CATEGORY_LABEL[cat])} "
            f"<span style=\"color:#999;font-weight:normal\">({len(items)})</span></h3>"
        )
        parts.append("<ul style=\"padding-left:18px\">")
        items.sort(key=lambda r: r.get("published", ""), reverse=True)
        for r in items:
            title = html.escape(r["title"] or "(no title)")
            url = html.escape(r["url"] or "#")
            src = html.escape(r["source_label"])
            summary = html.escape((r.get("summary") or "")[:280])
            parts.append(
                f"<li style=\"margin-bottom:8px\">"
                f"<a href=\"{url}\">{title}</a><br>"
                f"<span style=\"color:#888;font-size:90%\">{src}</span><br>"
                f"<span style=\"color:#444;font-size:90%\">{summary}</span>"
                f"</li>"
            )
        parts.append("</ul>")

    parts.append(
        "<hr style=\"margin-top:24px\"><p style=\"color:#999;font-size:85%\">"
        "Generated by mal-monitor (GitHub Actions). Edit sources in "
        "<code>mal-monitor/feeds/sources.yaml</code>.</p>"
    )
    parts.append("</body></html>")
    return "".join(parts)


def send(html_body: str, n_mentions: int) -> None:
    msg = EmailMessage()
    msg["Subject"] = f"[Mal monitor] {n_mentions} new mention(s) — " \
                     f"{datetime.now(timezone.utc).strftime('%Y-%m-%d')}"
    msg["From"] = os.environ["DIGEST_FROM"]
    msg["To"] = os.environ["DIGEST_TO"]
    msg.set_content("This digest requires an HTML-capable client.")
    msg.add_alternative(html_body, subtype="html")

    host = os.environ["DIGEST_SMTP_HOST"]
    port = int(os.environ["DIGEST_SMTP_PORT"])
    user = os.environ["DIGEST_SMTP_USER"]
    password = os.environ["DIGEST_SMTP_PASS"]

    with smtplib.SMTP(host, port) as s:
        s.starttls()
        s.login(user, password)
        s.send_message(msg)


def main() -> int:
    rows = load_recent(WINDOW_HOURS)
    if not rows:
        print("No new mentions; skipping digest.", file=sys.stderr)
        return 0
    body = render_html(rows)
    send(body, len(rows))
    print(f"Sent digest with {len(rows)} mention(s).", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
